version: '3'
services:
  react-app:
    build:
      # The context is the path where the Dockerfile is located -> wheere the project should be found
      context: .
      # The Dockerfile to be used DEV
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
      # DEVELOPMENT
      # Volumes: It's function is to map a folder from the host machine to a folder inside the container
      # so that the changes made in the host machine are reflected in the container
    volumes:
      # Do not try to map a folder against node_modules inside the container
      - /app/node_modules
      - .:/app # Map the current folder to the /app folder inside the container

  #Service for running tests
  react-app-test:
    build:
      # The context is the path where the Dockerfile is located -> wheere the project should be found
      context: .
      # The Dockerfile to be used DEV
      dockerfile: Dockerfile.dev
      # DEVELOPMENT
      # Volumes: It's function is to map a folder from the host machine to a folder inside the container
      # so that the changes made in the host machine are reflected in the container
    volumes:
      # Do not try to map a folder against node_modules inside the container
      - /app/node_modules
      - .:/app # Map the current folder to the /app folder inside the container
    #Override the default command in the Dockerfile, so once the container is up, it will run the tests
    command: [ "npm", "run", "test" ]
